M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue 22 Sep 2026 02:58:24 PM KST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-22T14:58:24+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X2.98Y46.23
X3.33Y53.63
X3.33Y4.63
X61.33Y53.63
X61.33Y4.63
X63.23Y46.2
T2
X43.73Y47.6
X54.35Y47.6
M30
